# Application general settings can sit here

# Email From addresses
#TODO this needs to be changed after confirming domain with sparkpost and tweeked before production deployment
bcc_email: "mymodernassets@gmail.com"
support_email: "hello@mymodernassets.com"
